# Generated by Django 4.0.6 on 2022-07-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.CharField(default='', max_length=20, unique=True)),
                ('reps', models.IntegerField(max_length=3)),
                ('sets', models.IntegerField(max_length=3)),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
